import type { KdvRow } from "@/features/tax/queries";

// Realistic KDV CSV input. Mixes Turkish names, multiple VAT rates, and
// includes a non-TRY row that the CSV builder is expected to omit (and
// surface in the comment line).
export const sampleKdvRows: KdvRow[] = [
  {
    id: "1",
    transaction_date: "2026-04-03",
    kind: "shipment_billing",
    currency: "TRY",
    amount: 118000,
    net_amount: 100000,
    vat_amount: 18000,
    vat_rate: 18,
    kdv_period: null,
    reference_number: "FAT-2026-0418",
    description: "İstanbul yurtiçi sevkiyat",
    contact_name: "İğneada Şirketi Ticaret A.Ş.",
    partner_name: null,
  },
  {
    id: "2",
    transaction_date: "2026-04-08",
    kind: "other_income",
    currency: "TRY",
    amount: 11800,
    net_amount: 10000,
    vat_amount: 1800,
    vat_rate: 18,
    kdv_period: null,
    reference_number: "DK-2026-04-001",
    description: "Danışmanlık geliri",
    contact_name: null,
    partner_name: "Çağdaş Yapı Ortaklığı",
  },
  {
    id: "3",
    transaction_date: "2026-04-11",
    kind: "supplier_invoice",
    currency: "TRY",
    amount: 47200,
    net_amount: 40000,
    vat_amount: 7200,
    vat_rate: 18,
    kdv_period: null,
    reference_number: "ALI-2026-0042",
    description: "Hammadde alımı — alüminyum profil",
    contact_name: null,
    partner_name: "Şahin Metal San. ve Tic. Ltd. Şti.",
  },
  {
    id: "4",
    transaction_date: "2026-04-15",
    kind: "expense",
    currency: "TRY",
    amount: 1180,
    net_amount: 1000,
    vat_amount: 180,
    vat_rate: 18,
    kdv_period: null,
    reference_number: "GID-2026-04-22",
    description: "Şirket aracı yakıt — Bahçelievler",
    contact_name: null,
    partner_name: null,
  },
  {
    id: "5",
    transaction_date: "2026-04-22",
    kind: "expense",
    currency: "TRY",
    amount: 8800,
    net_amount: 8000,
    vat_amount: 800,
    vat_rate: 10,
    kdv_period: null,
    reference_number: "GID-2026-04-23",
    description: "Ofis kırtasiye, baskı, kâğıt",
    contact_name: null,
    partner_name: null,
  },
  // Non-TRY row — should be skipped from the CSV body and counted in the
  // "non-TRY rows omitted" header comment.
  {
    id: "6",
    transaction_date: "2026-04-26",
    kind: "supplier_invoice",
    currency: "EUR",
    amount: 5900,
    net_amount: 5000,
    vat_amount: 900,
    vat_rate: 18,
    kdv_period: null,
    reference_number: "EUR-2026-008",
    description: "Avrupa malzeme alımı",
    contact_name: null,
    partner_name: "Müller GmbH",
  },
];
