-- Backfill the countries lookup with the ~90 ISO-3166-1 entries the original
-- seed (20260427140000_seed_countries.sql) skipped. Triggered by the contact
-- form having no entry for Cuba; rather than chase one country at a time, fill
-- in the rest of the UN-recognized sovereign states plus Palestine and Kosovo.
-- Idempotent via ON CONFLICT (code) DO NOTHING — safe to re-run.

INSERT INTO public.countries (code, name_en, name_tr, flag_emoji) VALUES
  -- Americas
  ('AG', 'Antigua and Barbuda', 'Antigua ve Barbuda', '🇦🇬'),
  ('BS', 'Bahamas', 'Bahamalar', '🇧🇸'),
  ('BB', 'Barbados', 'Barbados', '🇧🇧'),
  ('BZ', 'Belize', 'Belize', '🇧🇿'),
  ('BO', 'Bolivia', 'Bolivya', '🇧🇴'),
  ('CR', 'Costa Rica', 'Kosta Rika', '🇨🇷'),
  ('CU', 'Cuba', 'Küba', '🇨🇺'),
  ('DM', 'Dominica', 'Dominika', '🇩🇲'),
  ('DO', 'Dominican Republic', 'Dominik Cumhuriyeti', '🇩🇴'),
  ('EC', 'Ecuador', 'Ekvador', '🇪🇨'),
  ('SV', 'El Salvador', 'El Salvador', '🇸🇻'),
  ('GD', 'Grenada', 'Grenada', '🇬🇩'),
  ('GT', 'Guatemala', 'Guatemala', '🇬🇹'),
  ('GY', 'Guyana', 'Guyana', '🇬🇾'),
  ('HT', 'Haiti', 'Haiti', '🇭🇹'),
  ('HN', 'Honduras', 'Honduras', '🇭🇳'),
  ('JM', 'Jamaica', 'Jamaika', '🇯🇲'),
  ('NI', 'Nicaragua', 'Nikaragua', '🇳🇮'),
  ('PA', 'Panama', 'Panama', '🇵🇦'),
  ('PY', 'Paraguay', 'Paraguay', '🇵🇾'),
  ('KN', 'Saint Kitts and Nevis', 'Saint Kitts ve Nevis', '🇰🇳'),
  ('LC', 'Saint Lucia', 'Saint Lucia', '🇱🇨'),
  ('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent ve Grenadinler', '🇻🇨'),
  ('SR', 'Suriname', 'Surinam', '🇸🇷'),
  ('TT', 'Trinidad and Tobago', 'Trinidad ve Tobago', '🇹🇹'),

  -- Africa
  ('AO', 'Angola', 'Angola', '🇦🇴'),
  ('BJ', 'Benin', 'Benin', '🇧🇯'),
  ('BW', 'Botswana', 'Botsvana', '🇧🇼'),
  ('BF', 'Burkina Faso', 'Burkina Faso', '🇧🇫'),
  ('BI', 'Burundi', 'Burundi', '🇧🇮'),
  ('CV', 'Cape Verde', 'Yeşil Burun Adaları', '🇨🇻'),
  ('CF', 'Central African Republic', 'Orta Afrika Cumhuriyeti', '🇨🇫'),
  ('TD', 'Chad', 'Çad', '🇹🇩'),
  ('KM', 'Comoros', 'Komorlar', '🇰🇲'),
  ('CG', 'Republic of the Congo', 'Kongo Cumhuriyeti', '🇨🇬'),
  ('CD', 'Democratic Republic of the Congo', 'Demokratik Kongo Cumhuriyeti', '🇨🇩'),
  ('DJ', 'Djibouti', 'Cibuti', '🇩🇯'),
  ('GQ', 'Equatorial Guinea', 'Ekvator Ginesi', '🇬🇶'),
  ('ER', 'Eritrea', 'Eritre', '🇪🇷'),
  ('SZ', 'Eswatini', 'Esvatini', '🇸🇿'),
  ('GA', 'Gabon', 'Gabon', '🇬🇦'),
  ('GM', 'Gambia', 'Gambiya', '🇬🇲'),
  ('GN', 'Guinea', 'Gine', '🇬🇳'),
  ('GW', 'Guinea-Bissau', 'Gine-Bissau', '🇬🇼'),
  ('LS', 'Lesotho', 'Lesotho', '🇱🇸'),
  ('LR', 'Liberia', 'Liberya', '🇱🇷'),
  ('MG', 'Madagascar', 'Madagaskar', '🇲🇬'),
  ('MW', 'Malawi', 'Malavi', '🇲🇼'),
  ('MR', 'Mauritania', 'Moritanya', '🇲🇷'),
  ('MU', 'Mauritius', 'Mauritius', '🇲🇺'),
  ('MZ', 'Mozambique', 'Mozambik', '🇲🇿'),
  ('NA', 'Namibia', 'Namibya', '🇳🇦'),
  ('NE', 'Niger', 'Nijer', '🇳🇪'),
  ('RW', 'Rwanda', 'Ruanda', '🇷🇼'),
  ('ST', 'São Tomé and Príncipe', 'São Tomé ve Príncipe', '🇸🇹'),
  ('SC', 'Seychelles', 'Seyşeller', '🇸🇨'),
  ('SL', 'Sierra Leone', 'Sierra Leone', '🇸🇱'),
  ('SO', 'Somalia', 'Somali', '🇸🇴'),
  ('SS', 'South Sudan', 'Güney Sudan', '🇸🇸'),
  ('SD', 'Sudan', 'Sudan', '🇸🇩'),
  ('TG', 'Togo', 'Togo', '🇹🇬'),
  ('ZM', 'Zambia', 'Zambiya', '🇿🇲'),
  ('ZW', 'Zimbabwe', 'Zimbabve', '🇿🇼'),

  -- Asia
  ('AF', 'Afghanistan', 'Afganistan', '🇦🇫'),
  ('BT', 'Bhutan', 'Butan', '🇧🇹'),
  ('BN', 'Brunei', 'Brunei', '🇧🇳'),
  ('KH', 'Cambodia', 'Kamboçya', '🇰🇭'),
  ('LA', 'Laos', 'Laos', '🇱🇦'),
  ('MV', 'Maldives', 'Maldivler', '🇲🇻'),
  ('MN', 'Mongolia', 'Moğolistan', '🇲🇳'),
  ('MM', 'Myanmar', 'Myanmar', '🇲🇲'),
  ('NP', 'Nepal', 'Nepal', '🇳🇵'),
  ('KP', 'North Korea', 'Kuzey Kore', '🇰🇵'),
  ('LK', 'Sri Lanka', 'Sri Lanka', '🇱🇰'),
  ('TL', 'Timor-Leste', 'Doğu Timor', '🇹🇱'),

  -- Europe (microstates not already seeded)
  ('AD', 'Andorra', 'Andorra', '🇦🇩'),
  ('LI', 'Liechtenstein', 'Lihtenştayn', '🇱🇮'),
  ('MC', 'Monaco', 'Monako', '🇲🇨'),
  ('SM', 'San Marino', 'San Marino', '🇸🇲'),
  ('VA', 'Vatican City', 'Vatikan', '🇻🇦'),

  -- Oceania
  ('FJ', 'Fiji', 'Fiji', '🇫🇯'),
  ('KI', 'Kiribati', 'Kiribati', '🇰🇮'),
  ('MH', 'Marshall Islands', 'Marshall Adaları', '🇲🇭'),
  ('FM', 'Micronesia', 'Mikronezya', '🇫🇲'),
  ('NR', 'Nauru', 'Nauru', '🇳🇷'),
  ('PW', 'Palau', 'Palau', '🇵🇼'),
  ('PG', 'Papua New Guinea', 'Papua Yeni Gine', '🇵🇬'),
  ('WS', 'Samoa', 'Samoa', '🇼🇸'),
  ('SB', 'Solomon Islands', 'Solomon Adaları', '🇸🇧'),
  ('TO', 'Tonga', 'Tonga', '🇹🇴'),
  ('TV', 'Tuvalu', 'Tuvalu', '🇹🇻'),
  ('VU', 'Vanuatu', 'Vanuatu', '🇻🇺'),

  -- Disputed / commonly needed (XK is the de-facto ISO user-assigned code for Kosovo)
  ('PS', 'Palestine', 'Filistin', '🇵🇸'),
  ('XK', 'Kosovo', 'Kosova', '🇽🇰')
ON CONFLICT (code) DO NOTHING;
