-- Seed the countries lookup table. The contact form's country picker queries
-- public.countries directly; an empty table renders an empty dropdown, which
-- looks like a broken Select. Idempotent: ON CONFLICT DO NOTHING means re-runs
-- never overwrite manually edited rows.
-- Run this in the Supabase dashboard SQL editor. Do not run locally with
-- `supabase db push` — schema is applied manually.

-- Match dev-mode policy used elsewhere in the schema: RLS off until production
-- auth lands. Without this, anon reads return [] even after the seed lands.
alter table public.countries disable row level security;

INSERT INTO public.countries (code, name_en, name_tr, flag_emoji) VALUES
  ('AE', 'United Arab Emirates', 'Birleşik Arap Emirlikleri', '🇦🇪'),
  ('AL', 'Albania', 'Arnavutluk', '🇦🇱'),
  ('AM', 'Armenia', 'Ermenistan', '🇦🇲'),
  ('AR', 'Argentina', 'Arjantin', '🇦🇷'),
  ('AT', 'Austria', 'Avusturya', '🇦🇹'),
  ('AU', 'Australia', 'Avustralya', '🇦🇺'),
  ('AZ', 'Azerbaijan', 'Azerbaycan', '🇦🇿'),
  ('BA', 'Bosnia and Herzegovina', 'Bosna Hersek', '🇧🇦'),
  ('BD', 'Bangladesh', 'Bangladeş', '🇧🇩'),
  ('BE', 'Belgium', 'Belçika', '🇧🇪'),
  ('BG', 'Bulgaria', 'Bulgaristan', '🇧🇬'),
  ('BH', 'Bahrain', 'Bahreyn', '🇧🇭'),
  ('BR', 'Brazil', 'Brezilya', '🇧🇷'),
  ('BY', 'Belarus', 'Belarus', '🇧🇾'),
  ('CA', 'Canada', 'Kanada', '🇨🇦'),
  ('CH', 'Switzerland', 'İsviçre', '🇨🇭'),
  ('CI', 'Côte d''Ivoire', 'Fildişi Sahili', '🇨🇮'),
  ('CL', 'Chile', 'Şili', '🇨🇱'),
  ('CM', 'Cameroon', 'Kamerun', '🇨🇲'),
  ('CN', 'China', 'Çin', '🇨🇳'),
  ('CO', 'Colombia', 'Kolombiya', '🇨🇴'),
  ('CY', 'Cyprus', 'Kıbrıs', '🇨🇾'),
  ('CZ', 'Czechia', 'Çekya', '🇨🇿'),
  ('DE', 'Germany', 'Almanya', '🇩🇪'),
  ('DK', 'Denmark', 'Danimarka', '🇩🇰'),
  ('DZ', 'Algeria', 'Cezayir', '🇩🇿'),
  ('EE', 'Estonia', 'Estonya', '🇪🇪'),
  ('EG', 'Egypt', 'Mısır', '🇪🇬'),
  ('ES', 'Spain', 'İspanya', '🇪🇸'),
  ('ET', 'Ethiopia', 'Etiyopya', '🇪🇹'),
  ('FI', 'Finland', 'Finlandiya', '🇫🇮'),
  ('FR', 'France', 'Fransa', '🇫🇷'),
  ('GB', 'United Kingdom', 'Birleşik Krallık', '🇬🇧'),
  ('GE', 'Georgia', 'Gürcistan', '🇬🇪'),
  ('GH', 'Ghana', 'Gana', '🇬🇭'),
  ('GR', 'Greece', 'Yunanistan', '🇬🇷'),
  ('HK', 'Hong Kong', 'Hong Kong', '🇭🇰'),
  ('HR', 'Croatia', 'Hırvatistan', '🇭🇷'),
  ('HU', 'Hungary', 'Macaristan', '🇭🇺'),
  ('ID', 'Indonesia', 'Endonezya', '🇮🇩'),
  ('IE', 'Ireland', 'İrlanda', '🇮🇪'),
  ('IL', 'Israel', 'İsrail', '🇮🇱'),
  ('IN', 'India', 'Hindistan', '🇮🇳'),
  ('IQ', 'Iraq', 'Irak', '🇮🇶'),
  ('IR', 'Iran', 'İran', '🇮🇷'),
  ('IS', 'Iceland', 'İzlanda', '🇮🇸'),
  ('IT', 'Italy', 'İtalya', '🇮🇹'),
  ('JO', 'Jordan', 'Ürdün', '🇯🇴'),
  ('JP', 'Japan', 'Japonya', '🇯🇵'),
  ('KE', 'Kenya', 'Kenya', '🇰🇪'),
  ('KG', 'Kyrgyzstan', 'Kırgızistan', '🇰🇬'),
  ('KR', 'South Korea', 'Güney Kore', '🇰🇷'),
  ('KW', 'Kuwait', 'Kuveyt', '🇰🇼'),
  ('KZ', 'Kazakhstan', 'Kazakistan', '🇰🇿'),
  ('LB', 'Lebanon', 'Lübnan', '🇱🇧'),
  ('LT', 'Lithuania', 'Litvanya', '🇱🇹'),
  ('LU', 'Luxembourg', 'Lüksemburg', '🇱🇺'),
  ('LV', 'Latvia', 'Letonya', '🇱🇻'),
  ('LY', 'Libya', 'Libya', '🇱🇾'),
  ('MA', 'Morocco', 'Fas', '🇲🇦'),
  ('MD', 'Moldova', 'Moldova', '🇲🇩'),
  ('ME', 'Montenegro', 'Karadağ', '🇲🇪'),
  ('MK', 'North Macedonia', 'Kuzey Makedonya', '🇲🇰'),
  ('ML', 'Mali', 'Mali', '🇲🇱'),
  ('MT', 'Malta', 'Malta', '🇲🇹'),
  ('MX', 'Mexico', 'Meksika', '🇲🇽'),
  ('MY', 'Malaysia', 'Malezya', '🇲🇾'),
  ('NG', 'Nigeria', 'Nijerya', '🇳🇬'),
  ('NL', 'Netherlands', 'Hollanda', '🇳🇱'),
  ('NO', 'Norway', 'Norveç', '🇳🇴'),
  ('NZ', 'New Zealand', 'Yeni Zelanda', '🇳🇿'),
  ('OM', 'Oman', 'Umman', '🇴🇲'),
  ('PE', 'Peru', 'Peru', '🇵🇪'),
  ('PH', 'Philippines', 'Filipinler', '🇵🇭'),
  ('PK', 'Pakistan', 'Pakistan', '🇵🇰'),
  ('PL', 'Poland', 'Polonya', '🇵🇱'),
  ('PT', 'Portugal', 'Portekiz', '🇵🇹'),
  ('QA', 'Qatar', 'Katar', '🇶🇦'),
  ('RO', 'Romania', 'Romanya', '🇷🇴'),
  ('RS', 'Serbia', 'Sırbistan', '🇷🇸'),
  ('RU', 'Russia', 'Rusya', '🇷🇺'),
  ('SA', 'Saudi Arabia', 'Suudi Arabistan', '🇸🇦'),
  ('SE', 'Sweden', 'İsveç', '🇸🇪'),
  ('SG', 'Singapore', 'Singapur', '🇸🇬'),
  ('SI', 'Slovenia', 'Slovenya', '🇸🇮'),
  ('SK', 'Slovakia', 'Slovakya', '🇸🇰'),
  ('SN', 'Senegal', 'Senegal', '🇸🇳'),
  ('SY', 'Syria', 'Suriye', '🇸🇾'),
  ('TH', 'Thailand', 'Tayland', '🇹🇭'),
  ('TJ', 'Tajikistan', 'Tacikistan', '🇹🇯'),
  ('TM', 'Turkmenistan', 'Türkmenistan', '🇹🇲'),
  ('TN', 'Tunisia', 'Tunus', '🇹🇳'),
  ('TR', 'Türkiye', 'Türkiye', '🇹🇷'),
  ('TW', 'Taiwan', 'Tayvan', '🇹🇼'),
  ('TZ', 'Tanzania', 'Tanzanya', '🇹🇿'),
  ('UA', 'Ukraine', 'Ukrayna', '🇺🇦'),
  ('UG', 'Uganda', 'Uganda', '🇺🇬'),
  ('US', 'United States', 'Amerika Birleşik Devletleri', '🇺🇸'),
  ('UY', 'Uruguay', 'Uruguay', '🇺🇾'),
  ('UZ', 'Uzbekistan', 'Özbekistan', '🇺🇿'),
  ('VE', 'Venezuela', 'Venezuela', '🇻🇪'),
  ('VN', 'Vietnam', 'Vietnam', '🇻🇳'),
  ('YE', 'Yemen', 'Yemen', '🇾🇪'),
  ('ZA', 'South Africa', 'Güney Afrika', '🇿🇦')
ON CONFLICT (code) DO NOTHING;
